name = "benchlist"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[limits]
cpu_ms = 30000
subrequests = 100

[vars]
NEXT_PUBLIC_URL = "https://benchlist.pages.dev"
NEXT_PUBLIC_SUPABASE_URL = "https://tykpuotidmvkvbtqwzef.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5a3B1b3RpZG12a3ZidHF3emVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI2MzY5OTMsImV4cCI6MjA5ODIxMjk5M30.1mzh5O7j2DSO4XId5WbguQyvwjQC6onwpmkTVOdtlsA"
NEXT_PUBLIC_CONTACT_EMAIL = "jeffrinjames99@gmail.com"
CRON_API_KEY = "benchlist_cron_sk_9f8e7d6c5b4a3210feedcabb18170b1d15e5fa2c8b9a0d1e2f3a4b5c6d7e8f90"
