export const LAUNCH_LIMITS = {
  FREE_DAILY_LIMIT: 5,
  TOTAL_DAILY_LIMIT: 20,
} as const

export const USER_DAILY_LAUNCH_LIMIT = 1

export const PROJECT_LIMITS_VARIABLES = {
  TODAY_LIMIT: 20,
  YESTERDAY_LIMIT: 5,
  MONTH_LIMIT: 5,
  VIEW_ALL_PAGE_TODAY_YESTERDAY_LIMIT: 20,
  VIEW_ALL_PAGE_MONTH_LIMIT: 20,
} as const

export const LAUNCH_SETTINGS = {
  MIN_DAYS_AHEAD: 1,
  MAX_DAYS_AHEAD: 180,
  DAYS_PER_PAGE: 7,
  LAUNCH_HOUR_UTC: 8,
} as const

export const DATE_FORMAT = {
  DISPLAY: "EEE, MMM d, yyyy",
  DISPLAY_MONTH: "MMMM yyyy",
  DISPLAY_DAY: "EEE d",
  API: "yyyy-MM-dd",
  FULL: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
} as const

export const API_RATE_LIMITS = {
  SEARCH: {
    REQUESTS: 15,
    WINDOW: 60 * 1000,
  },
  DEFAULT: {
    REQUESTS: 10,
    WINDOW: 60 * 1000,
  },
} as const

export const UPVOTE_LIMITS = {
  ACTIONS_PER_WINDOW: 100,
  TIME_WINDOW_MS: 5 * 60 * 1000,
  TIME_WINDOW_MINUTES: 5,
  MIN_TIME_BETWEEN_ACTIONS_MS: 2000,
  MIN_TIME_BETWEEN_ACTIONS_SECONDS: 2,
  DEBOUNCE_TIME_MS: 500,
} as const

export const DOMAIN_AUTHORITY = 37
